/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('vue-element-plus-x')['Attachments']
    Bubble: typeof import('vue-element-plus-x')['Bubble']
    BubbleList: typeof import('vue-element-plus-x')['BubbleList']
    Conversations: typeof import('vue-element-plus-x')['Conversations']
    ElAvatar: typeof import('element-plus')['ElAvatar']
    ElButton: typeof import('element-plus')['ElButton']
    ElCollapse: typeof import('element-plus')['ElCollapse']
    ElCollapseItem: typeof import('element-plus')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus')['ElColorPicker']
    ElDialog: typeof import('element-plus')['ElDialog']
    ElDropdown: typeof import('element-plus')['ElDropdown']
    ElDropdownItem: typeof import('element-plus')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus')['ElDropdownMenu']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElImage: typeof import('element-plus')['ElImage']
    ElInput: typeof import('element-plus')['ElInput']
    ElInputNumber: typeof import('element-plus')['ElInputNumber']
    ElMention: typeof import('element-plus')['ElMention']
    ElPopover: typeof import('element-plus')['ElPopover']
    ElProgress: typeof import('element-plus')['ElProgress']
    ElRadioButton: typeof import('element-plus')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus')['ElScrollbar']
    ElSlider: typeof import('element-plus')['ElSlider']
    ElSwitch: typeof import('element-plus')['ElSwitch']
    ElTimeline: typeof import('element-plus')['ElTimeline']
    ElTimelineItem: typeof import('element-plus')['ElTimelineItem']
    ElTooltip: typeof import('element-plus')['ElTooltip']
    ElUpload: typeof import('element-plus')['ElUpload']
    FilesCard: typeof import('vue-element-plus-x')['FilesCard']
    MentionSender: typeof import('vue-element-plus-x')['MentionSender']
    Prompts: typeof import('vue-element-plus-x')['Prompts']
    Sender: typeof import('vue-element-plus-x')['Sender']
    Thinking: typeof import('vue-element-plus-x')['Thinking']
    ThoughtChain: typeof import('vue-element-plus-x')['ThoughtChain']
    Typewriter: typeof import('vue-element-plus-x')['Typewriter']
    Welcome: typeof import('vue-element-plus-x')['Welcome']
  }
}
